### PR TITLE
Add assess-with-filesystem

### PR DESCRIPTION
**Pull request by DamienCassou**
This work has been done by @Fuco1. I'm only responsible for a bug fix and for the adaptation to `assess` source code.

### CODE REVIEW

**Comment by Fuco1** [comment]
Out of curiosity, what was the bug?  Thanks for packaging this up btw :)

**Comment by DamienCassou** [comment]
I sent you an email about it. Didn't you get it?

The code you sent contained:

``` emacs
(defun with-buttercup-filesystem--make-parent (spec path)
  "If SPEC is a file name, create its parent directory rooted at PATH."
  (save-match-data
    (string-match "\\(.*\\)/" spec)
    (when (match-string 1 spec)
  (make-directory (concat path "/" (match-string 1 spec)) t))))
```

which I think is buggy because it calls `match-string` even if `string-match` fails. The new code is:

``` emacs
(defun assess-with-filesystem--make-parent (spec path)
  "If SPEC is a file name, create its parent directory rooted at PATH."
  (save-match-data
    (when (string-match "\\(.*\\)/" spec)
      (make-directory (concat path "/" (match-string 1 spec)) t))))
```

**Comment by phillord** [comment]
It looks like a really nice addition. 

Do both of you have copyright papers with FSF? I'm planning on adding assess to core!

**Comment by DamienCassou** [comment]
@phillord I do.

**Comment by Fuco1** [comment]
@phillord I have as well.

**Comment by phillord** [comment]
On master now! Thank you very much, and apologies for slow processing. Busy time of year.

**Pull request closed without merging**
