### PR TITLE
Fix unused variable issues

### PR DESCRIPTION
**Pull request by syohex**

### CODE REVIEW

**Comment by phillord** [comment]
Before I take these PRs (both good!), can I ask whether you have/would be willing to do Copyright Assignment for FSF. It's quite likely that this library will end up in Emacs or ELPA, so I'd like to get this in place.

If you don't know what I am talking about, then I'll send you details by email.

**Comment by syohex** [comment]
I don't do copyright assignment for FSF yet. Could you tell me how to do copyright assignment for FSF ?

**Comment by syohex** [comment]
Thanks for information.

**Comment by phillord** [comment]
I'll merge this now. Thanks for the contribution.

**Pull request merged**
